services:
  # A Docker web service
  - type: web
    name: JISSHU_BOT
    env: python
    startCommand: python3 bot.py
    buildCommand: pip install -r requirements.txt
    repo: https://github.com/Jisshubot/JISSHU_BOT.git # optional
    region: oregon # optional (defaults to oregon)
    plan: free # optional (defaults to starter)
    branch: JISSHU # optional (defaults to master)
    numInstances: 1 # optional (defaults to 1)
    healthCheckPath: /
    envVars:
      - key: ADMINS
        sync: false
      - key: API_ID
        sync: false
      - key: API_HASH
        sync: false
      - key: BOT_TOKEN
        sync: false
      - key: CHANNELS
        sync: false
      - key: DATABASE_URI
        sync: false
      - key: PICS
        sync: false
      - key: LOG_CHANNEL
        sync: false
      - key: PYTHON_VERSION
        sync: false 3.10.8
      - key: CHNL_LNK
        sync: false
        
