# Don't Remove Credit @movie_file_20
# Subscribe YouTube Channel For Amazing Bot @movie_file_20
# Ask Doubt on telegram @KingVJ01

services:
  # A Docker web service
  - type: web
    name: JISSHU_BOT 
    env: python
    startCommand: python3 bot.py
    buildCommand: pip3 install -U -r requirements.txt
    repo: https://github.com/Jisshubot/JISSHU_BOT.git # optional
    region: oregon # optional (defaults to oregon)
    plan: free # optional (defaults to starter)
    branch: JISSHU # optional (defaults to master)
    numInstances: 1 # optional (defaults to 1)
    healthCheckPath: /

#End of yaml
